/** Where each component on the board lives. The page resolves these to editor links on the server. */
export const BOARD_SOURCES = {
  logo: "packages/ui/src/components/brand/altruvex-logo.tsx",
  tokens: "packages/ui/src/styles/tokens.css",
  globals: "apps/www/app/globals.css",
  edges: "docs/edge-system-2026-09.md",
  magnetic: "apps/www/components/magnetic-button.tsx",
  magneticClasses: "packages/ui/src/www/button.ts",
  button: "packages/ui/src/components/primitives/button.tsx",
  arrow: "packages/ui/src/components/primitives/arrow-icon.tsx",
  input: "packages/ui/src/components/forms/input.tsx",
  checkbox: "packages/ui/src/components/forms/checkbox.tsx",
  switch: "packages/ui/src/components/forms/switch.tsx",
  segmented: "packages/ui/src/components/forms/segmented-control.tsx",
  select: "packages/ui/src/components/forms/select.tsx",
  badge: "packages/ui/src/components/data-display/badge.tsx",
  avatar: "packages/ui/src/components/data-display/avatar.tsx",
  kbd: "packages/ui/src/components/primitives/kbd.tsx",
  loading: "packages/ui/src/components/feedback/loading-icon.tsx",
  skeleton: "packages/ui/src/components/feedback/skeleton.tsx",
  stat: "apps/admin/components/os/stat-tile.tsx",
  listRow: "apps/admin/components/os/list-row.tsx",
  pager: "apps/admin/components/os/pager.tsx",
  tabs: "apps/admin/components/os/tab-nav.tsx",
  empty: "apps/admin/components/os/empty-state.tsx",
  planned: "apps/admin/components/os/planned.tsx",
  heading: "apps/www/components/sections/section-heading.tsx",
  eyebrow: "packages/ui/src/www/eyebrow.tsx",
  emphasis: "packages/ui/src/www/emphasis.tsx",
  plan: "apps/www/components/sections/plan-summary.tsx",
  endCta: "apps/www/components/sections/section-end-cta.tsx",
  tooltip: "packages/ui/src/components/overlays/tooltip.tsx",
  menu: "packages/ui/src/components/overlays/dropdown-menu.tsx",
  accordion: "packages/ui/src/components/overlays/accordion.tsx",
  alertDialog: "packages/ui/src/components/overlays/alert-dialog.tsx",
  sheet: "packages/ui/src/components/overlays/sheet.tsx",
  drawer: "packages/ui/src/components/overlays/drawer.tsx",
  popover: "packages/ui/src/components/overlays/popover.tsx",
  calendar: "packages/ui/src/components/forms/calendar.tsx",
  datePicker: "packages/ui/src/components/forms/date-picker.tsx",
  label: "packages/ui/src/components/forms/label.tsx",
  surface: "packages/ui/src/components/primitives/surface.tsx",
  separator: "packages/ui/src/components/primitives/separator.tsx",
  toaster: "packages/ui/src/components/feedback/sonner.tsx",
  siteInput: "packages/ui/src/www/input.tsx",
  siteLabel: "packages/ui/src/www/label.tsx",
  siteSelect: "packages/ui/src/www/select.tsx",
  siteDatePicker: "packages/ui/src/www/date-picker.tsx",
  siteCalendar: "packages/ui/src/www/calendar.tsx",
  siteTimePicker: "packages/ui/src/www/time-picker.tsx",
  siteAccordion: "packages/ui/src/www/accordion.tsx",
  siteDrawer: "packages/ui/src/www/drawer.tsx",
  siteSegmented: "packages/ui/src/www/segmented-control.tsx",
} as const;

export type SourceKey = keyof typeof BOARD_SOURCES;
